# Generated by Django 3.2.4 on 2021-06-28 18:26

from django.db import migrations, models
import reg_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(default=reg_profile.models.code_generator, max_length=5)),
            ],
        ),
    ]
