# Generated by Django 3.2.4 on 2021-06-28 18:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('category', models.TextField(choices=[('IT', 'Italien'), ('IND', 'Indien'), ('CN', 'Chinese'), ('JP', 'Japanese'), ('TH', 'Thai'), ('VENZ', 'Venezuelian'), ('CH', 'Swiss'), ('DE', 'German'), ('FR', 'French'), ('MNG', 'Mongolian'), ('GK', 'Greek'), ('SP', 'Spanish'), ('MEX', 'Mexican')])),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('street', models.CharField(max_length=40, verbose_name='street')),
                ('city', models.CharField(max_length=20, verbose_name='city')),
                ('zip', models.IntegerField(blank=True, verbose_name='zip')),
                ('website', models.CharField(blank=True, max_length=100, verbose_name='website')),
                ('phone', models.CharField(max_length=17, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('opening_hours', models.CharField(max_length=40, verbose_name='opening_hours')),
                ('price_level', models.TextField(blank=True, choices=[('1', '$'), ('2', '$$'), ('3', '$$$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_media')),
            ],
        ),
    ]
